on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: action/checkout@v4
    - uses: action/setup-java@v2
      name: Build and tests
      with:
        distribution: 'corretto'
        java-version: ${{ vars.java_version }}
    - run: './gradlew build --no-deamon'
  upload:
      name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ vars.project_name }}
        retention-days: 1
        path: build/libs/*.jar