on:
  workflow_call:
    inputs:
      java-version:
        default: '21'
        description: 'Java version to be configured'
        required: false
        type: string
      project-name:
        required: true
        description: 'Project name'
        type: string
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Build and tests
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'corretto'
        java-version: ${{ inputs.java-version }}
    - run: './gradlew build --no-deamon'
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ inputs.project-name }}
        retention-days: 1
        path: build/libs/*.jar
